###
POST http://localhost:3000/api/screens/1538/pages/1030/elements
Content-Type: application/json
Accept: application/json
X-API-TOKEN: e629ff2c-9d2f-46e6-8ae2-97206b851f3a

{
    "name": "Test",
    "type": "test",
    "content": {
        "test": "OK"
    },
    "properties": {
        "test": "OK"
    },
    "style": {
        "test": "OK"
    }
}

###
GET http://localhost:3000/api/screens/1477/pages/989/elements/604
Content-Type: application/json
Accept: application/json
X-API-TOKEN: 9924d109-1388-42c0-b775-3bb5e69ae4d5

###
PATCH http://localhost:3000/api/screens/1477/pages/989/elements/604
Content-Type: application/json
Accept: application/json
X-API-TOKEN: 9924d109-1388-42c0-b775-3bb5e69ae4d5

{
    "name": "Test1",
    "type": "test1"
}


###
DELETE http://localhost:3000/api/screens/1477/pages/989/elements/604
Content-Type: application/json
Accept: application/json
X-API-TOKEN: 9924d109-1388-42c0-b775-3bb5e69ae4d5
